import Head from 'next/head';
import Footer from "./footer";
import Header from "./header";

const Layout = ({ children }) => {
    return ( 
      <div>
        <Head>
          <title>Notifications</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header/>
            { children }
        <Footer/>
      </div>
    );
}
 
export default Layout;